# -*- coding: utf-8 -*-
"""age counter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBJiaiDwFzIrXhlO-Ma0Op062sAcXSZ6
"""

import time

class age:
    def __init__(self):
        self.birth=input("생년월일 8자리를 띄어쓰기 없이 입력해 주십시오")
        self.year = int(self.birth[0:4])
        self.month = int(self.birth[4:6])
        self.day = int(self.birth[6::])
        print("{}년, {}월, {}일이 맞습니까?".format(self.year, self.month, self.day))
        for i in self.birth:
            if i not in '0123456789':
                print("잘못된 입력입니다. 다시 입력해 주세요")
                self.__init__()
            else:
                self.answer=input("Yes : 1, No : 2 >> ")
                if self.answer=='1':
                    self.birthday()
                    return
                else :
                    self.__init__()

    def birthday(self):
        date=time.localtime()[0:3]
        t_year = date[0]
        t_month = date[1]
        t_day = date[2]
        print("오늘은 {}년 {}월 {}일 입니다.".format(t_year, t_month, t_day))
        print("한국식 나이는 {}살 입니다.".format(t_year-self.year+1))
        if (t_month*100+t_day)-int(self.birth[4::])>-1:
            print("미국식 나이는 {}살 입니다.".format(t_year-self.year))
        else:
            print("미국식 나이는 {}살 입니다.".format(t_year-self.year-1))

a=age()