# -*- coding: utf-8 -*-
"""qu_errors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MOfCMNL9ljWjHoZCcZCXDrgP324IhCAq
"""

#name error - abc라는 변수가 정의되지 않았음.
#print(abc)
abc=1
print(abc)

#name error - prnt라는 함수가 정의되지 않음
#prnt(1)
print(1)

#index error - tmp의 index는 0밖에 없으므로, tmp[1]은 호출할 수 없다.
tmp=[2]
#print(tmp[1])
tmp.append(2)
print(tmp[1])

#value error - str type인 'a'를 숫자 타입인 int로 형변환 하려고 해서 발생한 에러
print(type('a'))
int('a')

#type error - 리스트 타입인 tmp를 숫자 타입인 float으로 형변환 하려고 하여 발생한 에러
print(type(tmp))
#float(tmp)
float(tmp[0])

#syntax error - for 뒤에 : 가 빠져있음.
sum=0
for i in range(10)
    sum+=i
print(sum)

#syntax error - for 뒤에 : 가 빠져있음.
sum=0
for i in range(10):
    sum+=i
print(sum)

