# Generated by Django 3.2.18 on 2023-03-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
