# Generated by Django 3.2.18 on 2023-03-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(default='study', max_length=20),
        ),
    ]
