# Generated by Django 3.2.18 on 2023-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(default='study', max_length=20, null=True),
        ),
    ]
